[build]
  command = "npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/discord/*"
  to = "/.netlify/functions/auth-discord-:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
